name = "sharex-r2-cloudflare-workers"
account_id = "9b4e8a5306252de7d3ebd878e5e80e27"
workers_dev = false
routes = [
	{pattern = "i.kaij.tech/*", zone_name = "kaij.tech"},
]

compatibility_date = "2022-04-22"
main = "./dist/index.mjs"

[build]
command = "npm run build"

[[r2_buckets]]
bucket_name = "sharex-files"
preview_bucket_name = "sharex-files"
binding = "R2_BUCKET"
